export type ResponseUserModel = {
    id: string,
    email: string,
    name: string,
    avatarUrl: string,
    dateOfBirth?: Date | null,
    createdAt: Date,
    updatedAt?: Date | null,
    bio?: string | null,
    location?: string | null,
    posts: string[],
    followers: string[],
    following: string[],
    isFollowing?: boolean,
}